[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "cartpole"
version = "0.0.0"
requires-python = ">=3.8"
dependencies = [
]

[project.optional-dependencies]
dev = []

[project.scripts]
cartpole = "cartpole.cartpole:main"
